# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: eDAST Scan
        run: |
          echo Updating Hosts File
          sudo echo "3.235.23.166 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
          echo starting eDAST Scan
          curl --location --request POST "https://fortify.cyberxdemo.com:11443/api/v2/scans/start-scan-cicd" --header "Authorization: FORTIFYTOKEN ${{ secrets.CI_TOKEN }}" --header "Content-Type: application/json" --data-raw '{"cicdToken": "${{ secrets.DAST_ID }}"}'
